services:
  #back
  web:
    container_name: briefing_api
    restart: always
    build:
      context: .
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - default

  postgres:
    container_name: briefing_db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-briefing}
    networks:
      - default

volumes:
  briefing_db:
    driver: local

networks:
  default: